### ISSUE TITLE
Keep the solution in Mastermind.cs

### ISSUE THREAD

**Issue by granalberto** [jfeliz16/MyGam#1]
The requirements need to be improved for matching this, so don't worry about this issue because itś not on you.

All the solution needs to be written in the file `Mastermind.cs`, its name cannot be changed and the namespace **MUST** keep named `Mastermind`.

**Comment by jfeliz16** [comment]
Ready.

**Comment by granalberto** [comment]
I can see that you made some changes. However, our tests are still failing because you didn't modify accordint to the new version of the template.

Please read again the information in http://zvitech.com/recruitment/. I'm sure you will note some changes and will be very easy for you to apply a patch so our tests can run.

**Comment by jfeliz16** [comment]
i had not seen the new template. Ready, you can check out again.
